appId: "fr.chobert.chobchat"
productName: "ChobChat"
linux:
  executableName: "chobchat"
  target:
    - target: deb
      arch:
        - armv7l
mac:
  target:
    - target: dmg
      arch:
        - x64
