appId: "fr.chobert.chobchat"
extraMetadata:
  main: "main.js"
afterSign: notarize.js
files:
  - from: "dist/main/"
    to: "./"
    filter: ["**/*"]
  - from: "dist/renderer/"
    to: "./"
    filter: ["**/*"]
  - package.json
  - "entitlements.mac.plist"
productName: "ChobChat"
linux:
  executableName: "chobchat"
  category: "Internet"
  protocols:
    - name: chobchat
      schemes:
        - chobchat
  target:
    - target: appImage
      arch:
        - x64
        - armv7l
        - arm64
mac:
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: "entitlements.mac.plist"
  entitlementsInherit: "entitlements.mac.plist"
  target:
    - target: dmg
      arch:
        - universal
    - target: zip
      arch:
        - universal
