appId: "fr.chobert.chobchat"
extraMetadata:
  main: "main.js"
files:
  - from: "dist/main/"
    to: "./"
    filter: ["**/*"]
  - from: "dist/renderer/"
    to: "./"
    filter: ["**/*"]
  - package.json
productName: "ChobChat"
linux:
  executableName: "chobchat"
  target:
    - target: deb
      arch:
        - arm64
mac:
  target:
    - target: dmg
      arch:
        - x64
