appId: "fr.chobert.chobchat"
extraMetadata:
  main: "main.js"
files:
  - from: "dist/main/"
    to: "./"
    filter: ["**/*"]
  - from: "dist/renderer/"
    to: "./"
    filter: ["**/*"]
  - package.json
productName: "ChobChat"
linux:
  executableName: "chobchat"
  category: "Internet"
  protocols:
    - name: chobchat
      schemes:
        - chobchat
  target:
    - target: appImage
      arch:
        - x64
        - armv7l
        - arm64
mac:
  target:
    - target: dmg
      arch:
        - universal
    - target: zip
      arch:
        - universal
