---
name: release

on:
  workflow_call:
    inputs:
      build_run_id:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    outputs:
      package_version: ${{ steps.retrieve-version.outputs.package_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Get Package Version
        id: retrieve-version
        run: |
          PKG_VERSION=$(jq -r .version mobile/package.json)
          echo "::set-output name=package_version::$PKG_VERSION"
      - name: Download all artifacts
        uses: bitwarden/gh-actions/download-artifacts@23433be15ed6fd046ce12b6889c5184a8d9c8783
        with:
          workflow: build.yml
          run_id: ${{ github.events.inputs.build_run_id }}
      - name: Create release
        uses: ncipollo/release-action@95215a3cb6e6a1908b3c44e00b4fdb15548b1e09 # v2.8.5
        env:
          PKG_VERSION: ${{ steps.retrieve-version.outputs.package_version }}
        with:
          artifacts: "ChobChat-${{ env.PKG_VERSION }}-armv7l.AppImage,
            ChobChat-${{ env.PKG_VERSION }}-arm64.AppImage
            ChobChat-${{ env.PKG_VERSION }}.AppImage,
            latest-linux.yml,
            ChobChat-${{ env.PKG_VERSION }}-universal-mac.zip,
            ChobChat-${{ env.PKG_VERSION }}-universal.dmg,
            latest-mac.yml"
          commit: ${{ github.sha }}
          tag: v${{ env.PKG_VERSION }}
          name: Version ${{ env.PKG_VERSION }}
          body: "<insert release notes here>"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
