---
name: release

on:
  workflow_call:
    inputs:
      build_run_id:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    outputs:
      package_version: ${{ steps.retrieve-version.outputs.package_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Get Package Version
        id: retrieve-version
        run: |
          PKG_VERSION=$(jq -r .version mobile/package.json)
          echo "::set-output name=package_version::$PKG_VERSION"
      # - name: Check to make sure Desktop release version has been bumped
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     latest_ver=$(hub release -L 1 -f '%T')
      #     latest_ver=${latest_ver:1}
      #     echo "Latest version: $latest_ver"
      #     ver=${{ steps.retrieve-version.outputs.package_version }}
      #     echo "Version: $ver"
      #     if [ "$latest_ver" = "$ver" ] && \
      #     [ "${{ github.event.inputs.release_type }}" == "Initial Release" ]; then
      #       echo "Version has not been bumped!"
      #       exit 1
      #     fi
      # - name: Get branch name
      #   id: branch
      #   run: |
      #     BRANCH_NAME=$(basename ${{ github.ref }})
      #     echo "::set-output name=branch-name::$BRANCH_NAME"
      - name: Download all artifacts
        uses: bitwarden/gh-actions/download-artifacts@23433be15ed6fd046ce12b6889c5184a8d9c8783
        with:
          workflow: build.yml
          # workflow_conclusion: success
          run_id: ${{ github.events.inputs.build_run_id }}
      - name: Create release
        uses: ncipollo/release-action@95215a3cb6e6a1908b3c44e00b4fdb15548b1e09 # v2.8.5
        env:
          PKG_VERSION: ${{ steps.retrieve-version.outputs.package_version }}
        with:
          artifacts: "ChobChat-${{ env.PKG_VERSION }}-armv7l.AppImage,
            ChobChat-${{ env.PKG_VERSION }}.AppImage,
            latest-linux.yml,
            ChobChat-${{ env.PKG_VERSION }}-universal-mac.zip,
            ChobChat-${{ env.PKG_VERSION }}-universal.dmg,
            latest-mac.yml"
          commit: ${{ github.sha }}
          tag: v${{ env.PKG_VERSION }}
          name: Version ${{ env.PKG_VERSION }}
          body: "<insert release notes here>"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
